/**
 * Shunya ECC — Mathematical Library (static / GitHub Pages build)
 * Fetches books.json (generated by generate-manifest.js), then
 * renders the full collection UI: tree, grid, search, filters, PDF modal.
 */

'use strict';

// ─── State ────────────────────────────────────────────────────────────────────

const state = {
  tree:       [],   // raw nested tree from books.json
  allBooks:   [],   // flat list of every book node
  activePath: '',   // active folder ('' = show all)
  query:      '',   // search string
  typeFilter: 'all',
};

// ─── DOM refs ────────────────────────────────────────────────────────────────

const $ = id => document.getElementById(id);

const els = {
  treeNav:      $('tree-nav'),
  bookGrid:     $('book-grid'),
  emptyState:   $('empty-state'),
  loadingState: $('loading-state'),
  sectionTitle: $('section-title'),
  itemCount:    $('item-count'),
  searchInput:  $('search-input'),
  breadcrumb:   $('breadcrumb'),
  collapseAll:  $('collapse-all'),
  filterPills:  document.querySelectorAll('.filter-pill'),

  modal:        $('pdf-modal'),
  modalBackdrop:$('modal-backdrop'),
  pdfFrame:     $('pdf-frame'),
  modalTitle:   $('modal-book-title'),
  modalAuthor:  $('modal-author'),
  modalType:    $('modal-type-badge'),
  modalClose:   $('modal-close'),
  modalOpenTab: $('modal-open-tab'),
  modalDownload:$('modal-download'),
  modalUrl:     $('modal-url'),
  detailDesc:   $('detail-description'),
  detailTags:   $('detail-tags'),
  dlAuthor:     $('dl-author'),
  dlYear:       $('dl-year'),
  dlType:       $('dl-type'),
  dlPages:      $('dl-pages'),
};

// ─── Utilities ────────────────────────────────────────────────────────────────

const cap = s => s ? s.charAt(0).toUpperCase() + s.slice(1) : '';
const esc = s => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;')
  .replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function getBookUrl(book) {
  return book?.url || book?.pdfUrl || '';
}

function typesetNode(node) {
  if (window.MathJax?.typesetPromise && node) {
    return window.MathJax.typesetPromise([node]).catch(() => {});
  }
  return Promise.resolve();
}

/** Recursively flatten tree → array of book nodes with ancestry info */
function flattenBooks(nodes, ancestors = []) {
  const books = [];
  for (const node of nodes) {
    if (node.kind === 'book') {
      books.push({ ...node, _ancestors: [...ancestors] });
    } else if (node.kind === 'folder' && node.children?.length) {
      books.push(...flattenBooks(node.children, [...ancestors, node]));
    }
  }
  return books;
}

/** Count all books under a node */
function countBooks(node) {
  if (node.kind === 'book') return 1;
  return (node.children || []).reduce((n, c) => n + countBooks(c), 0);
}

/** True if bookPath is at or under activePath */
function isUnderPath(bookPath, activePath) {
  if (!activePath) return true;
  return bookPath === activePath || bookPath.startsWith(activePath + '/');
}

/** Find a node by path in the tree */
function getNodeByPath(target) {
  if (!target) return null;
  function walk(nodes) {
    for (const n of nodes) {
      if (n.path === target) return n;
      if (n.children) { const f = walk(n.children); if (f) return f; }
    }
    return null;
  }
  return walk(state.tree);
}

// ─── Sidebar tree ─────────────────────────────────────────────────────────────

function renderTree(nodes) {
  els.treeNav.innerHTML = '';
  if (!nodes.length) {
    els.treeNav.innerHTML = `
      <p style="padding:1rem 1.25rem;font-size:0.8rem;color:var(--text-dim);line-height:1.6">
        No collections yet.<br>
        Add books to <code>books/</code>, run<br>
        <code>node generate-manifest.js</code>,<br>
        then commit <code>books.json</code>.
      </p>`;
    return;
  }
  nodes.forEach(n => els.treeNav.appendChild(buildTreeNode(n)));
}

function buildTreeNode(node) {
  return node.kind === 'book' ? buildTreeBook(node) : buildTreeFolder(node);
}

function buildTreeFolder(node) {
  const count   = countBooks(node);
  const wrapper = document.createElement('div');
  wrapper.className = 'tree-folder';

  const toggle = document.createElement('button');
  toggle.className = 'tree-folder-toggle';
  toggle.setAttribute('aria-expanded', 'false');
  toggle.innerHTML = `
    <svg class="folder-chevron" viewBox="0 0 12 12" fill="none">
      <path d="M4 2L8 6L4 10" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <svg class="folder-icon" viewBox="0 0 16 16" fill="none">
      <path d="M2 4C2 3.448 2.448 3 3 3H6.586C6.851 3 7.105 3.105 7.293 3.293L8.293 4.293C8.48 4.48 8.735 4.586 9 4.586H13C13.552 4.586 14 5.034 14 5.586V12C14 12.552 13.552 13 13 13H3C2.448 13 2 12.552 2 12V4Z" stroke="currentColor" stroke-width="1.3" stroke-linejoin="round"/>
    </svg>
    <span class="folder-name">${esc(node.name)}</span>
    ${count ? `<span class="folder-count">${count}</span>` : ''}`;

  toggle.addEventListener('click', () => {
    const open = wrapper.classList.toggle('open');
    toggle.setAttribute('aria-expanded', open);
    if (open) setActivePath(node.path);
  });

  wrapper.appendChild(toggle);

  if (node.children?.length) {
    const childWrap = document.createElement('div');
    childWrap.className = 'tree-children';
    node.children.forEach(c => childWrap.appendChild(buildTreeNode(c)));
    wrapper.appendChild(childWrap);
  }

  return wrapper;
}

function buildTreeBook(node) {
  const wrapper = document.createElement('div');
  wrapper.className = 'tree-book';

  const btn = document.createElement('button');
  btn.className = 'tree-book-btn';
  btn.innerHTML = `
    <svg class="book-icon-sm" viewBox="0 0 16 16" fill="none">
      <rect x="3" y="2" width="10" height="12" rx="1.5" stroke="currentColor" stroke-width="1.3"/>
      <line x1="6" y1="5" x2="10" y2="5" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/>
      <line x1="6" y1="8" x2="10" y2="8" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/>
    </svg>
    <span>${esc(node.title || node.name)}</span>`;

  btn.addEventListener('click', () => openModal(node));
  wrapper.appendChild(btn);
  return wrapper;
}

// ─── Breadcrumb ───────────────────────────────────────────────────────────────

function renderBreadcrumb(activePath) {
  const parts = activePath ? activePath.split('/') : [];

  let html = `
    <button class="crumb crumb-home" data-path="">
      <svg viewBox="0 0 16 16" fill="none">
        <path d="M2 6.5L8 2L14 6.5V14H10V10H6V14H2V6.5Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
      </svg>
      Library
    </button>`;

  parts.forEach((part, i) => {
    const partPath  = parts.slice(0, i + 1).join('/');
    const isCurrent = i === parts.length - 1;
    html += `<span class="crumb-sep" aria-hidden="true">/</span>`;
    html += isCurrent
      ? `<span class="crumb crumb-current">${esc(part)}</span>`
      : `<button class="crumb" data-path="${esc(partPath)}">${esc(part)}</button>`;
  });

  els.breadcrumb.innerHTML = html;
  els.breadcrumb.querySelectorAll('button[data-path]').forEach(btn => {
    btn.addEventListener('click', () => setActivePath(btn.dataset.path));
  });
}

// ─── Grid ─────────────────────────────────────────────────────────────────────

function getVisibleBooks() {
  return state.allBooks.filter(book => {
    if (!isUnderPath(book.path, state.activePath)) return false;
    if (state.typeFilter !== 'all' && book.type !== state.typeFilter) return false;
    if (state.query) {
      const q    = state.query.toLowerCase();
      const text = [book.title, book.author, book.description, ...(book.tags || [])]
        .join(' ').toLowerCase();
      if (!text.includes(q)) return false;
    }
    return true;
  });
}

function getChildFolders() {
  if (!state.activePath) return state.tree.filter(n => n.kind === 'folder');
  const node = getNodeByPath(state.activePath);
  return node ? (node.children || []).filter(n => n.kind === 'folder') : [];
}

function renderGrid() {
  const books   = getVisibleBooks();
  const folders = state.query ? [] : getChildFolders();

  const activeNode = getNodeByPath(state.activePath);
  els.sectionTitle.textContent = state.activePath
    ? (activeNode?.name || state.activePath.split('/').pop())
    : 'All Collections';

  const total = books.length;
  els.itemCount.textContent = `${total} ${total === 1 ? 'item' : 'items'}`;

  if (!books.length && !folders.length) {
    els.bookGrid.innerHTML = '';
    els.emptyState.classList.remove('hidden');
    return;
  }
  els.emptyState.classList.add('hidden');

  let html = '';

  folders.forEach(folder => {
    const count = countBooks(folder);
    html += `
      <div class="folder-card" tabindex="0" role="button"
           data-folder-path="${esc(folder.path)}"
           aria-label="Open folder ${esc(folder.name)}">
        <div class="folder-card-icon">
          <svg viewBox="0 0 24 24" fill="none">
            <path d="M3 7C3 6.448 3.448 6 4 6H9.586C9.851 6 10.105 6.105 10.293 6.293L11.707 7.707C11.895 7.895 12.149 8 12.414 8H20C20.552 8 21 8.448 21 9V18C21 18.552 20.552 19 20 19H4C3.448 19 3 18.552 3 18V7Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
          </svg>
        </div>
        <div class="folder-card-info">
          <div class="folder-card-name">${esc(folder.name)}</div>
          <div class="folder-card-sub">${count} ${count === 1 ? 'item' : 'items'}</div>
        </div>
        <svg style="width:16px;height:16px;color:var(--text-dim)" viewBox="0 0 16 16" fill="none">
          <path d="M6 4L10 8L6 12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </div>`;
  });

  books.forEach(book => {
    const type    = book.type || 'book';
    const tags    = (book.tags || []).slice(0, 5);
    const tagsHtml = tags.map(t => `<span class="tag">${esc(t)}</span>`).join('');
    const bookUrl = getBookUrl(book);
    const footerLabel = bookUrl && bookUrl !== book.pdfUrl ? 'Open link' : 'Open PDF';

    html += `
      <article class="book-card" tabindex="0" role="button"
               data-book-path="${esc(book.path)}"
               aria-label="Open ${esc(book.title || book.name)}">
        <div class="card-top">
          <span class="type-badge ${esc(type)}">${cap(type)}</span>
          ${book.year ? `<span class="year-chip">${esc(String(book.year))}</span>` : ''}
        </div>
        <h2 class="card-title">${esc(book.title || book.name)}</h2>
        ${book.author      ? `<p class="card-author">${esc(book.author)}</p>` : ''}
        ${book.description ? `<p class="card-desc">${esc(book.description)}</p>` : ''}
        ${tagsHtml         ? `<div class="card-tags">${tagsHtml}</div>` : ''}
        <div class="card-footer">
          ${bookUrl ? `<a class="card-link" href="${esc(bookUrl)}" target="_blank" rel="noopener" onclick="event.stopPropagation()">${esc(footerLabel)}</a>` : ''}
          <span class="card-open-btn">
            Details
            <svg viewBox="0 0 16 16" fill="none">
              <path d="M3 8H13M13 8L9 4M13 8L9 12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          </span>
        </div>
      </article>`;
  });

  els.bookGrid.innerHTML = html;
  requestAnimationFrame(() => typesetNode(els.bookGrid));

  els.bookGrid.querySelectorAll('.folder-card').forEach(card => {
    const handler = () => setActivePath(card.dataset.folderPath);
    card.addEventListener('click', handler);
    card.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') handler(); });
  });

  els.bookGrid.querySelectorAll('.book-card').forEach(card => {
    const book = state.allBooks.find(b => b.path === card.dataset.bookPath);
    if (!book) return;
    const handler = () => openModal(book);
    card.addEventListener('click', handler);
    card.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') handler(); });
  });
}

function openBookFromHash() {
  const hash = parseHash();
  if (!hash || hash.key !== 'book') return;
  const book = state.allBooks.find(b => b.path === hash.value);
  if (book) {
    const folderPath = book.path.split('/').slice(0, -1).join('/');
    if (folderPath) setActivePath(folderPath);
    openModal(book, false);
  }
}

// ─── Navigation ───────────────────────────────────────────────────────────────

function setActivePath(path) {
  state.activePath = path;
  renderBreadcrumb(path);
  renderGrid();
}

// ─── Modal ────────────────────────────────────────────────────────────────────

function setHashForBook(book) {
  const encoded = encodeURIComponent(book.path);
  if (window.location.hash !== `#book=${encoded}`) {
    window.location.hash = `#book=${encoded}`;
  }
}

function parseHash() {
  const hash = window.location.hash.slice(1);
  if (!hash) return null;
  const [key, value] = hash.split('=');
  return value ? { key, value: decodeURIComponent(value) } : null;
}

function openModal(book, updateHash = true) {
  const type = book.type || 'book';
  const bookUrl = getBookUrl(book);

  if (updateHash) setHashForBook(book);

  els.modalTitle.textContent  = book.title  || book.name;
  els.modalAuthor.textContent = book.author || 'Unknown author';
  els.modalType.textContent   = cap(type);
  els.modalType.className     = `type-badge ${type}`;

  els.pdfFrame.src            = book.pdfUrl;
  els.modalOpenTab.href       = bookUrl || book.pdfUrl;
  els.modalOpenTab.textContent = bookUrl && bookUrl !== book.pdfUrl ? 'Open link' : 'Open in tab';
  els.modalUrl.href           = bookUrl || book.pdfUrl;
  els.modalUrl.textContent     = bookUrl || book.pdfUrl || 'No URL available';
  els.modalUrl.style.display   = bookUrl || book.pdfUrl ? 'inline-flex' : 'none';
  els.modalDownload.href      = book.pdfUrl;
  els.modalDownload.download  = `${book.title || book.name}.pdf`;

  els.detailDesc.textContent  = book.description || 'No description provided.';
  els.dlAuthor.textContent    = book.author || '—';
  els.dlYear.textContent      = book.year   || '—';
  els.dlType.textContent      = cap(type);
  els.dlPages.textContent     = book.pages  || '—';

  els.detailTags.innerHTML = (book.tags || []).length
    ? book.tags.map(t => `<span class="tag">${esc(t)}</span>`).join('')
    : '<span style="font-size:0.8rem;color:var(--text-dim)">No tags</span>';

  els.modal.hidden          = false;
  document.body.style.overflow = 'hidden';
  requestAnimationFrame(() => typesetNode(els.modal));
  els.modalClose.focus();
}

function closeModal() {
  els.modal.hidden          = true;
  els.pdfFrame.src          = '';
  document.body.style.overflow = '';
}

// ─── Load books.json ──────────────────────────────────────────────────────────

async function loadCollection() {
  try {
    const res = await fetch('books.json');

    if (res.status === 404) {
      throw new Error('books.json not found — run <code>node generate-manifest.js</code> first.');
    }
    if (!res.ok) {
      throw new Error(`Failed to load books.json (HTTP ${res.status})`);
    }

    const tree = await res.json();

    state.tree     = tree;
    state.allBooks = flattenBooks(tree);

    els.loadingState.classList.add('hidden');
    renderTree(tree);
    renderBreadcrumb('');
    renderGrid();
    openBookFromHash();

  } catch (err) {
    els.loadingState.innerHTML = `
      <div class="empty-glyph" style="color:var(--text-dim)">⚠</div>
      <p class="empty-title" style="color:var(--text-muted)">Could not load collection</p>
      <p class="empty-sub">${err.message}</p>`;
    console.error('[Shunya ECC]', err);
  }
}

// ─── Events ───────────────────────────────────────────────────────────────────

let searchTimer;
els.searchInput.addEventListener('input', () => {
  clearTimeout(searchTimer);
  searchTimer = setTimeout(() => {
    state.query = els.searchInput.value.trim();
    renderGrid();
  }, 180);
});

document.addEventListener('keydown', e => {
  if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
    e.preventDefault();
    els.searchInput.focus();
    els.searchInput.select();
  }
  if (e.key === 'Escape' && !els.modal.hidden) closeModal();
});

window.addEventListener('hashchange', () => {
  if (window.location.hash.startsWith('#book=')) {
    openBookFromHash();
  } else if (!window.location.hash) {
    closeModal();
  }
});

els.filterPills.forEach(pill => {
  pill.addEventListener('click', () => {
    els.filterPills.forEach(p => p.classList.remove('active'));
    pill.classList.add('active');
    state.typeFilter = pill.dataset.type;
    renderGrid();
  });
});

els.collapseAll?.addEventListener('click', () => {
  els.treeNav.querySelectorAll('.tree-folder.open').forEach(f => {
    f.classList.remove('open');
    f.querySelector('[aria-expanded]')?.setAttribute('aria-expanded', 'false');
  });
});

els.modalClose.addEventListener('click', closeModal);
els.modalBackdrop.addEventListener('click', closeModal);

// ─── Init ─────────────────────────────────────────────────────────────────────
loadCollection();
